[build-system]
requires = ['flit_core >=2,<4']
build-backend = 'flit_core.buildapi'

[tool.flit.metadata]
module = 'rcdev'
author = 'José'
classifiers = [ 'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',]
description-file = 'README.md'
requires = [
    'ansible',
    'astpretty',
    'asttokens',
    'python-box[all]',
    'click',
    'click_completion',
    'colorama',
    'colorlog',
    'python-decouple',
    'devtools[pygments]',
    'distro',
    'dnspython',
    'python-dotenv',
    'dpath',
    'environs',
    'envtoml',
    'executing',
    'flit',
    'funcy',
    'furl',
    'gitpython',
    'icecream',
    'inflect',
    'intervaltree',
    'iocextract',
    'ipaddress',
    'jsonpickle',
    'jupyter',
    'python-libnmap',
    'loguru',
    'mackup',
    'mashumaro',
    'more_itertools',
    'motor',
    'nested_lookup',
    'notifiers',
    'numpy',
    'pandas',
    'paramiko',
    'pickledb',
    'pip',
    'psutil',
    'pydantic',
    'pypattyrn',
    'pymetasploit3',
    'pymongo[tls]',
    'pytest',
    'pyyaml',
    'requests[security]',
    'retry',
    'returns',
    'rich',
    'semver',
    'setuptools',
    'shell_proc',
    'shellingham',
    'structlog',
    'sty',
    'taskflow',
    'tenacity',
    'thefuck',
    'tinydb',
    'typer[all]',
    'toolz',
    'tqdm',
    'urllib3',
    'varname',
    'verboselogs',
    'wakatime',
    'xmltodict',
    'types-typed_ast',
    'types-click',
    'types-contextvars',
    'types-decorator',
    'types-docutils',
    'types-frozendict',
    'types-ipaddress',
    'types-nmap',
    'types-PyYAML',
    'types-retry',
    'types-requests',
    'types-singledispatch',
    'types-toml',
    'types-typing-extensions',
    'typing_json',
    'boltons',
    'cachetools',
    'dataclass_factory',
    'datamodel-code-generator',
    'frozendict',
    'geoip2',
    'glom',
    'heartrate',
    'janus',
    'jsonpath_ng',
    'matplotlib',
    'orjson',
    'pure_eval',
    'seaborn',
    'snoop',
    'sorcery',
    'stack_data',
    'ujson',
]
